language: python
services:
    - mysql
python:
    - "3.5"
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS wechat_ticket;'
    - mv configs.example.json configs.json
# command to install dependencies
install:
    - sudo apt-get install python3-mysqldb
    - pip install -r requirements.txt

script:
    - python manage.py test
